wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.10
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695765190.953925
    t:
      1:
      - 55
      3:
      - 23
      4: 3.10.13
      5: 0.15.10
      8:
      - 5
