name: rlhf
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python
  - pip
  - transformers
  - datasets
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy 
  - black
  - flake8
  - isort
  - pudb
  - tqdm
  - wandb
  - pip:
    - trl
