wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.10
    framework: huggingface
    huggingface_version: 4.33.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695228744.624468
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 84
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 84
      3:
      - 23
      4: 3.10.13
      5: 0.15.10
      6: 4.33.1
      8:
      - 5
